# 配置文件
print=true
debug=true

[server]
local = true
port = 81
# addr = "0.0.0.0"
# engine=rdx
xrt="2"

[front2]
f2show="/site/list123456"
suff=[".html",".htm",".css",".map",".js",".ts",".json"]
rootpath=["/zgg","/demo"]

[front2.indexs]
"/zgg"="index.htm"
"/demo"="demo.html"

[s3cdn]
# s3 端口
endpoint=""
# s3 账号
access=""
# s3 秘钥
secret=""
# s3 存储桶
bucket=""
# s3 区域
region=""
# s3 根目录
rootdir=""
# 访问地址, CDN域名， 包含桶信息，比如 //[bucket].x.y.z or //x.y.z/[bucket]
domain=""
# 对应用的内容进行重写
rewrite=false
