# kubectl apply  -f 09-sidecar-01.yaml -n default
# kubectl delete -f 09-sidecar-01.yaml -n default
# 边车注入修改服务

apiVersion: v1
kind: Service
metadata:
  name: ksidecar
spec:
  ports:
  - name: https
    port: 443
  - name: http
    port: 80
  selector:
    app: ksidecar

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksidecar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ksidecar
  template:
    metadata:
      labels:
        app: ksidecar
    spec:
      serviceAccountName: ksidecar
      containers:
        - name: ksidecar
          image: suisrc/k8skit:1.3.xx-sidecar
          imagePullPolicy: IfNotPresent
          args:
            - --dual
            - --sidecarDatasource
            - 'user:pass@tcp(mysql.base.svc:3306)/cfg?charset=utf8&parseTime=True&loc=Asia%2FShanghai'
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 4
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 4

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksidecar
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ksidecar
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ksidecar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ksidecar
subjects:
  - kind: ServiceAccount
    name: ksidecar
    namespace: default
